### ISSUE TITLE
Upgrade debug to v2.6.9

### ISSUE THREAD

**Issue by joseluisq** [pinojs/pino-debug#13]
Actually `pino-debug@1.0.5` uses `debug@2.6.0`, because of [this security vulnerability](https://nodesecurity.io/advisories/534) an upgrade of debug to v2.6.9 should fix it. 

__Update:__ it's already done at b892b08

**Comment by joseluisq** [comment]
Note: That issue is already fixed in [v2.6.9](https://github.com/visionmedia/debug/releases/tag/2.6.9)

Refs: https://github.com/visionmedia/debug/pull/504

**Comment by mcollina** [comment]
I am a bit lost. What are you proposing apart from #11?

**Comment by joseluisq** [comment]
> I am a bit lost. What are you proposing apart from #11?

#11 is not my PR. I purpose only the upgrading of that dependency, because I'm using pino-debug@1.0.5. But I saw the pino-debug is not compatible with `debug v3`

**Comment by joseluisq** [comment]
Anyway, a intermediately upgrade of debug to v2.6.9 it would be more logic. correct me if wrong.

**Comment by joseluisq** [comment]
v1.0.5: https://unpkg.com/pino-debug@1.0.5/package.json (`debug v2.6.0`)
Master: `debug v2.6.9` (https://github.com/pinojs/pino-debug/commit/b892b0806af7a7418106b8ab07735e49e78d8e4c)

`package.json` on master branch contains `debug v2.6.9`

**Comment by mcollina** [comment]
I’m still lost. What do you want us to do? Is the release on npm not in sync to what is on master?

**Comment by joseluisq** [comment]
yep, basically bump a new pino-debug release with debug v2.6.9

**Comment by mcollina** [comment]
Released v1.0.6.

**Comment by joseluisq** [comment]
👍
