### ISSUE TITLE
TypeError: Cannot read property 'platform' of undefined when dependent module is using core-js module

### ISSUE THREAD

**Issue by kileyhykawy** [pinojs/pino-debug#16]
**Steps to Reproduce**
1. In your project, include a dependent module that includes `core-js` module (specifically `library/modules/es6.promise.js`). In my specific case, I was using Loopback which includes `strong-globalize@2.10.0` which includes `g11n-pipeline@2.0.4` which includes `swagger-client@3.4.4` which includes `babel-runtime@6.26.0`.
2. Preload `pino-debug` when starting node `node -r pino-debug build/src/server/server.js`

**Actual Results**
Exception log:
```
TypeError: Cannot read property 'platform' of undefined
    at pinoDebugWrappedRequire (/Users/kiley/code/lumin/luminlife/lumin-api/node_modules/core-js/library/modules/es6.promise.js:1:344)
    at Object.<anonymous> (/Users/kiley/code/lumin/luminlife/lumin-api/node_modules/core-js/library/modules/es6.promise.js:2:15)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at pinoDebugWrappedRequire (/Users/kiley/code/lumin/luminlife/lumin-api/node_modules/core-js/library/fn/promise.js:1:731)
```

The problem ends up in how `core-js/library/modules/es6.promise.js` is setting a variable name `process` to the global `process` object. Here is how the code looks to Node:
```
(function(exports, require, module, __filename, __dirname) {
    ;require = (function(req) {
        ;var Object = ({}).constructor;
        return Object.setPrototypeOf(function pinoDebugWrappedRequire(s) {
            ;var dirname = __dirname.slice(-22);
            var pathToPinoDebug = '/Users/kiley/code/lumin/luminlife/lumin-api/node_modules/pino-debug/debug.js';
            ;if (process.platform === 'win32') {
                ;dirname = dirname.replace(/\\/g, '/');
            }
            ;;if (s === './debug' && /node_modules\/debug/.test(dirname)) {
                ;var dbg = req(pathToPinoDebug);
                var real = req(s);
                Object.assign(dbg, real);
                Object.defineProperty(real, 'save', {
                    get: function() {
                        ;Object.defineProperty(real, 'save', {
                            value: dbg.save
                        });
                        return real.save;
                    },
                    configurable: true
                });
                return dbg;
            }
            ;return req(s);
        }, req);
    }(require));

...

    var process = global.process;
```

Since the variable name is declared, it is actually undefined when `pino-debug` is trying to access it. I suspect that the fix is to change `process.platform` to `global.process.platform`. This ensures we use the global process object rather than something that someone else has defined. I'll give it a try and make a PR.

**Comment by lukaszewczak** [comment]
Hi @kileyhykawy , thank you once again for reporting this issue with great description. I will now closed this issue after I merged your PR.

**Comment by jfgodoy** [comment]
Hi, can you publish the fixed version in npm?
thanks you.

**Comment by lukaszewczak** [comment]
Hi @jfgodoy , the new version was published. There was small delay, because I was waiting for credentials.
