### ISSUE TITLE
Package broken?

### ISSUE THREAD

**Issue by DeividasJackus** [pinojs/pino-debug#21]
Am I doing something incorrectly?

```
$ npm i pino-debug
+ pino-debug@1.1.3
added 31 packages in 0.915s
$ DEBUG=* node -r pino-debug -e 'require("debug")("test")("hello world")'
  test hello world +0ms
```

**Comment by deividasjackus** [comment]
@mcollina I saw #20 but for whatever reason decided that since I'm not using debug@4 this is a different issue 🤣 Sorry, lack of caffeine!

```$ grep version node_modules/debug/package.json
  "version": "3.2.5"
```

**Comment by deividasjackus** [comment]
It appears that the breaking change was also published to `debug@3.2.5`. It works fine with `debug@3.1.0` however.

**Comment by mcollina** [comment]
If you would like to send a PR to restore functionality, it would be highly
appreciated?

Il giorno mar 18 set 2018 alle 17:48 Deividas Jackus <
notifications@github.com> ha scritto:

**Comment by franher** [comment]
hello, I had the same issue.

I forced debug to v3.1.0 on debug-pino v1.1.3 and is working for me.

Previously I got the following error:
```console
/node_modules/pino-debug/debug.js:7
    throw Error('debug called before pino-debug initialized,' +
    ^

Error: debug called before pino-debug initialized,register pino-debug at the top of your entry point
    at debug (/***/node_modules/pino-debug/debug.js:7:11)
    at Object.<anonymous> (/***/node_modules/finalhandler/index.js:14:29)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at pinoDebugWrappedRequire (/***/node_modules/express/lib/application.js:1:762)
```

@mcollina what kind of PR are you asking for? fix the dependency of debug to don't use ^ ? If it's the solution, I can do it. Thank you.

**Comment by mcollina** [comment]
I would very much prefer an actual fix to the issue.
