### ISSUE TITLE
failing tests with debug v2.6.1  (problem with debug)

### ISSUE THREAD

**Issue by davidmarkclements** [pinojs/pino-debug#4]
it's actually to do with https://github.com/visionmedia/debug/issues/425

but it does mean we need to find a way around any modules that use v2.6.1 when 
mapping functionality is used

**Comment by busybeaver** [comment]
Hi,

any update on this?

Seems like `debug` <= 2.6.8 is vulnerable to some ReDoS:
https://nodesecurity.io/advisories/534

**Comment by lukaszewczak** [comment]
Hi @davidmarkclements ,

I think that after last PR, this issue can be closed.

**Comment by davidmarkclements** [comment]
not quite, it does resolve the DoS issue in =<2.6.8, but `debug` current major is 3, which will be much more work to integrate with

@lukaszewczak if you're interested in making pino-debug compatible with debug v3 and you submit a PR then I'd love to make you co-contributor if that's something you'd want

**Comment by lukaszewczak** [comment]
Oh I see, ok, I will investigate `debug` current version , and how to make `pino-debug` compatible with it. I will try to prepare PR for this.

I will be glad to become **co-contributor**, but could you please describe the difference between contributor and co-contributor ? :-)

**Comment by mcollina** [comment]
This should be fixed!
