### ISSUE TITLE
Pino-debug wrapper messes up the stacktrace line numbers

### ISSUE THREAD

**Issue by noxxious** [pinojs/pino-debug#6]
When enabled, due to a module wrapper all the original line numbers are shifted, which causes a huge confusion when investigating stack traces.

**Comment by davidmarkclements** [comment]
ironically anti-debugging friendly huh

can you show me example output

I can probably solve this by putting the injected stuff on one line and prefixing the first LOC with it (that same way the Node module wrapper does)

**Comment by noxxious** [comment]
Added example repo in #https://github.com/noxxious/pino-debug-issue-6

**Comment by busybeaver** [comment]
Any update on this issue? 😃
Needed to remove this module temporary... since it makes debugging and error tracing unnecessarily complicated when running a larger codebase.

**Comment by davidmarkclements** [comment]
fixed!

published to npm as 1.0.4
